### ISSUE TITLE
Plugin status

### ISSUE THREAD

**Issue by jonarrien** [rsense/SublimeRsense#1]
Hey, 

I think this plugin could be really great for Ruby developers like me using Sublime Text. I tried it in ST3 and at least is not working for me.  I've already noticed different imports in source code that looks you are trying to maintain compatibility between ST2 and ST3.

I would like to know the actual status and if you are looking for any kind of collaboration. I really would like to help somehow. Feel free to contact me if you want to talk in detail about it.

Regards

**Comment by edubkendo** [comment]
Hello @jonarrien , I'd love some help. I've been swamped at work and haven't been able to give any time to this project lately which is frustrating. I also kind of needed a break from it.  The first thing that would be super useful is if you could re-work this plugin to use http and json to communicate with rsense, like the Atom plugin does.

I have ST3 on my machine, and that's what I tested it on, but I was trying to maintain compatibility with ST2 as you say.  I'm probably willing to break that at this point (Is anyone still using ST2?).  

Beyond that there are a a number of other things that need done in the larger rsense codebase, and I'd love to see someone tackling some of those.

**Comment by jonarrien** [comment]
Thanks for the info @edubkendo. I am a bit swamped at work too, but when having time, I'll try analyze the source code and see if I can contribute somehow.

**Comment by edubkendo** [comment]
:+1:  awesome, looking forward to that
